### ISSUE TITLE
Add both Stop IDs for each tablet

### ISSUE THREAD

**Issue by jlawrenceCambridge** [LiveBus/displayV1#5] opened 2018-08-16 12:36 UTC
Ezra will send you the spreadsheet with this information

**Comment by maxtkc** [comment] 2018-08-16 15:19
This means that you still want the individual url's for each location.
Tablet A: https://livebus.github.io/displayV1/a/auto.html

**Comment by jlawrenceCambridge** [comment] 2018-08-16 16:22
Ezra and Jess created an FAQ document that tells people how to get to the stop ID, so it’s fine to not have an individual URL unless it’s not that difficult to do.

**Comment by maxtkc** [comment] 2018-08-16 17:51
Could you clarify what the issue is here? If it isn't still an issue, you can close this. Also, if you could try to avoid adding all of the extra text in the comments that would be great. Maybe if you comment directly on github...

**Comment by jlawrenceCambridge** [comment] 2018-08-16 17:54
I'm not adding any extra text :)
Each tablet (business) should have two stop IDs associated. I know that you are working on it, but you asked that I put all the requests into github.  This one relates to the list of Stop IDs that Ezra is sending you.

**Closed as completed** 2018-08-17 13:13 UTC
Labels: needs clarification
